### ISSUE TITLE
Remove and archive 'Names of Things' page

### ISSUE THREAD

**Issue by RobTobias123** [centrica-engineering/nucleus-docs#188]
### Outcome
Outdated 'Names of Things' page removed from docs. Archived in Internal handbook.

### Scope

- [x] Archive to Internal handbook
- [x] Delete from Docs
- [x] PR
- [ ] Merge

**Comment by RobTobias123** [comment]
Cloudflare page build fails on PR - I guess because the page has been deleted. Please advise if there is another process I need to follow to remove the page? @jholt1 

Log...
2023-05-24T08:18:13.091009Z	Cloning repository...
2023-05-24T08:18:14.183468Z	From https://github.com/centrica-engineering/nucleus-docs
2023-05-24T08:18:14.184178Z	 * branch            670494870f8d54bd8b7522b8218c553ee0d53719 -> FETCH_HEAD
2023-05-24T08:18:14.18436Z	
2023-05-24T08:18:14.334635Z	HEAD is now at 6704948 Delete names-of-things.md
2023-05-24T08:18:14.335181Z	
2023-05-24T08:18:14.453288Z	
2023-05-24T08:18:14.486408Z	Success: Finished cloning repository files
2023-05-24T08:18:15.989733Z	Installing dependencies
2023-05-24T08:18:15.998021Z	Python version set to 2.7
2023-05-24T08:18:19.307287Z	v12.18.0 is already installed.
2023-05-24T08:18:20.495789Z	Now using node v12.18.0 (npm v6.14.4)
2023-05-24T08:18:20.667896Z	Started restoring cached build plugins
2023-05-24T08:18:20.684062Z	Finished restoring cached build plugins
2023-05-24T08:18:21.11309Z	Attempting ruby version 2.7.1, read from environment
2023-05-24T08:18:22.664829Z	Using /opt/buildhome/.rvm/gems/ruby-2.7.1
2023-05-24T08:18:23.700582Z	Using PHP version 5.6
2023-05-24T08:18:23.797396Z	5.2.5 is already installed.
2023-05-24T08:18:23.816449Z	Using Swift version 5.2.5
2023-05-24T08:18:23.817022Z	Started restoring cached node modules
2023-05-24T08:18:23.831271Z	Finished restoring cached node modules
2023-05-24T08:18:24.170834Z	Installing NPM modules using NPM version 6.14.4
2023-05-24T08:18:25.981803Z	npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
2023-05-24T08:18:47.822327Z	
2023-05-24T08:18:47.823054Z	> core-js@3.17.3 postinstall /opt/buildhome/repo/node_modules/core-js
2023-05-24T08:18:47.82332Z	> node -e "try{require('./postinstall')}catch(e){}"
2023-05-24T08:18:47.823475Z	
2023-05-24T08:18:47.932721Z	[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
2023-05-24T08:18:47.933087Z	
2023-05-24T08:18:47.933269Z	[96mThe project needs your help! Please consider supporting of core-js:[0m
2023-05-24T08:18:47.933401Z	[96m>[94m https://opencollective.com/core-js [0m
2023-05-24T08:18:47.933533Z	[96m>[94m https://patreon.com/zloirock [0m
2023-05-24T08:18:47.933667Z	[96m>[94m https://paypal.me/zloirock [0m
2023-05-24T08:18:47.933805Z	[96m>[94m bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz [0m
2023-05-24T08:18:47.933956Z	
2023-05-24T08:18:47.934104Z	[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
2023-05-24T08:18:47.934253Z	
2023-05-24T08:18:47.945527Z	
2023-05-24T08:18:47.945808Z	> core-js-pure@3.17.3 postinstall /opt/buildhome/repo/node_modules/core-js-pure
2023-05-24T08:18:47.945973Z	> node -e "try{require('./postinstall')}catch(e){}"
2023-05-24T08:18:47.946106Z	
2023-05-24T08:18:49.242903Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
2023-05-24T08:18:49.243348Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2023-05-24T08:18:49.243561Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
2023-05-24T08:18:49.243701Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2023-05-24T08:18:49.244175Z	
2023-05-24T08:18:49.249705Z	added 1410 packages from 695 contributors and audited 1418 packages in 23.314s
2023-05-24T08:18:50.073996Z	
2023-05-24T08:18:50.074338Z	198 packages are looking for funding
2023-05-24T08:18:50.074489Z	  run `npm fund` for details
2023-05-24T08:18:50.074614Z	
2023-05-24T08:18:50.075051Z	found 373 vulnerabilities (12 low, 80 moderate, 229 high, 52 critical)
2023-05-24T08:18:50.075267Z	  run `npm audit fix` to fix them, or `npm audit` for details
2023-05-24T08:18:50.107546Z	NPM modules installed
2023-05-24T08:18:50.16888Z	Installing Hugo 0.54.0
2023-05-24T08:18:50.871221Z	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
2023-05-24T08:18:50.875929Z	Started restoring cached go cache
2023-05-24T08:18:50.892405Z	Finished restoring cached go cache
2023-05-24T08:18:50.984149Z	go version go1.14.4 linux/amd64
2023-05-24T08:18:50.997522Z	go version go1.14.4 linux/amd64
2023-05-24T08:18:51.002815Z	Installing missing commands
2023-05-24T08:18:51.003153Z	Verify run directory
2023-05-24T08:18:51.00336Z	Executing user command: npm run build
2023-05-24T08:18:51.47183Z	
2023-05-24T08:18:51.472165Z	> nucleus-docs@0.0.0 build /opt/buildhome/repo
2023-05-24T08:18:51.472321Z	> npm run getTokens && docusaurus build
2023-05-24T08:18:51.472435Z	
2023-05-24T08:18:51.79659Z	
2023-05-24T08:18:51.796945Z	> nucleus-docs@0.0.0 getTokens /opt/buildhome/repo
2023-05-24T08:18:51.797148Z	> node scripts/get-tokens.js
2023-05-24T08:18:51.797725Z	
2023-05-24T08:18:51.914844Z	Fetching tokens
2023-05-24T08:18:53.537842Z	> Saved tokens/ns-tokens.json
2023-05-24T08:18:55.755716Z	> Saved tokens/ns-tokens.js
2023-05-24T08:18:58.365917Z	
2023-05-24T08:18:58.366491Z	[en] Creating an optimized production build...
2023-05-24T08:18:58.698889Z	error building locale=en
2023-05-24T08:18:58.699336Z	Error: Bad sidebars file.
2023-05-24T08:18:58.699589Z	These sidebar document ids do not exist:
2023-05-24T08:18:58.699735Z	- foundations/names-of-things,
2023-05-24T08:18:58.69988Z	
2023-05-24T08:18:58.700003Z	Available document ids=
2023-05-24T08:18:58.700121Z	- archive/becoming-nucleus
2023-05-24T08:18:58.700253Z	- archive/best-practices
2023-05-24T08:18:58.700371Z	- archive/contributing
2023-05-24T08:18:58.700513Z	- archive/creating-icons
2023-05-24T08:18:58.700649Z	- archive/creating-illustrations
2023-05-24T08:18:58.700771Z	- archive/need-something-new
2023-05-24T08:18:58.700923Z	- archive/optimise-images
2023-05-24T08:18:58.701059Z	- community/contribute-to-documentation
2023-05-24T08:18:58.70119Z	- community/contribute-to-nucleus
2023-05-24T08:18:58.701324Z	- community/events
2023-05-24T08:18:58.70253Z	- community/releases
2023-05-24T08:18:58.702856Z	- community/vanilla-first
2023-05-24T08:18:58.70323Z	- community/working-agreement
2023-05-24T08:18:58.703466Z	- components/ns-accordion
2023-05-24T08:18:58.704199Z	- components/ns-appointment-picker
2023-05-24T08:18:58.704402Z	- components/ns-article
2023-05-24T08:18:58.70453Z	- components/ns-card
2023-05-24T08:18:58.704669Z	- components/ns-caveat
2023-05-24T08:18:58.704781Z	- components/ns-column
2023-05-24T08:18:58.704911Z	- components/ns-content
2023-05-24T08:18:58.705037Z	- components/ns-cta
2023-05-24T08:18:58.705147Z	- components/ns-datepicker
2023-05-24T08:18:58.705329Z	- components/ns-download
2023-05-24T08:18:58.705558Z	- components/ns-editorial
2023-05-24T08:18:58.705724Z	- components/ns-expander
2023-05-24T08:18:58.705882Z	- components/ns-fieldset
2023-05-24T08:18:58.706001Z	- components/ns-footer
2023-05-24T08:18:58.706124Z	- components/ns-form
2023-05-24T08:18:58.70623Z	- components/ns-header
2023-05-24T08:18:58.706338Z	- components/ns-highlighter
2023-05-24T08:18:58.70644Z	- components/ns-icon
2023-05-24T08:18:58.706558Z	- components/ns-illustration
2023-05-24T08:18:58.706663Z	- components/ns-image
2023-05-24T08:18:58.706764Z	- components/ns-inputter
2023-05-24T08:18:58.706879Z	- components/ns-landmark
2023-05-24T08:18:58.707Z	- components/ns-live
2023-05-24T08:18:58.707116Z	- components/ns-lockup
2023-05-24T08:18:58.70722Z	- components/ns-panel
2023-05-24T08:18:58.707322Z	- components/ns-password
2023-05-24T08:18:58.707423Z	- components/ns-pill
2023-05-24T08:18:58.707525Z	- components/ns-price
2023-05-24T08:18:58.707627Z	- components/ns-product-card
2023-05-24T08:18:58.707728Z	- components/ns-progress
2023-05-24T08:18:58.707829Z	- components/ns-selector
2023-05-24T08:18:58.707947Z	- components/ns-skeleton
2023-05-24T08:18:58.708092Z	- components/ns-skyline
2023-05-24T08:18:58.708204Z	- components/ns-slot-picker
2023-05-24T08:18:58.70831Z	- components/ns-standout
2023-05-24T08:18:58.708417Z	- components/ns-tab
2023-05-24T08:18:58.708528Z	- components/ns-table
2023-05-24T08:18:58.708634Z	- components/ns-tabs
2023-05-24T08:18:58.708738Z	- components/ns-testimonial
2023-05-24T08:18:58.708864Z	- components/ns-timeline
2023-05-24T08:18:58.708981Z	- components/ns-video
2023-05-24T08:18:58.709096Z	- components/nsx-address-selector
2023-05-24T08:18:58.709201Z	- components/nsx-footer
2023-05-24T08:18:58.709314Z	- components/nsx-header
2023-05-24T08:18:58.709419Z	- components/nsx-marketing-consent
2023-05-24T08:18:58.709528Z	- components/nsx-product-card-overview
2023-05-24T08:18:58.709636Z	- foundations/colours
2023-05-24T08:18:58.709738Z	- foundations/icons
2023-05-24T08:18:58.709859Z	- foundations/illustrations
2023-05-24T08:18:58.709978Z	- foundations/lists
2023-05-24T08:18:58.710095Z	- foundations/modular-scale
2023-05-24T08:18:58.710202Z	- foundations/photography
2023-05-24T08:18:58.710319Z	- foundations/structure
2023-05-24T08:18:58.710432Z	- foundations/typography
2023-05-24T08:18:58.710538Z	- foundations/viewports
2023-05-24T08:18:58.71065Z	- getting-started/accessibility
2023-05-24T08:18:58.710753Z	- getting-started/brand
2023-05-24T08:18:58.710867Z	- getting-started/design-tokens
2023-05-24T08:18:58.710981Z	- getting-started/introduction
2023-05-24T08:18:58.711114Z	- getting-started/our-process
2023-05-24T08:18:58.71123Z	- getting-started/principles
2023-05-24T08:18:58.711348Z	- getting-started/working-with-nucleus
2023-05-24T08:18:58.711462Z	- internal/ns-calendar
2023-05-24T08:18:58.711588Z	- page-types/article
2023-05-24T08:18:58.711695Z	- page-types/confirmation
2023-05-24T08:18:58.711799Z	- page-types/editorial
2023-05-24T08:18:58.711918Z	- page-types/guide
2023-05-24T08:18:58.71204Z	- page-types/home
2023-05-24T08:18:58.712151Z	- page-types/hub
2023-05-24T08:18:58.712263Z	- page-types/product
2023-05-24T08:18:58.712377Z	- page-types/roadblock
2023-05-24T08:18:58.712792Z	- page-types/start
2023-05-24T08:18:58.71295Z	- page-types/stopgap
2023-05-24T08:18:58.713085Z	- patterns/asking-for-information
2023-05-24T08:18:58.713213Z	- patterns/experiences
2023-05-24T08:18:58.713451Z	- patterns/journeys
2023-05-24T08:18:58.713569Z	- patterns/loading
2023-05-24T08:18:58.71373Z	- patterns/messaging
2023-05-24T08:18:58.713865Z	- patterns/telephone-numbers
2023-05-24T08:18:58.714016Z	    at Object.checkSidebarsDocIds (/opt/buildhome/repo/node_modules/@docusaurus/plugin-content-docs/lib/sidebars.js:294:19)
2023-05-24T08:18:58.714144Z	    at loadVersion (/opt/buildhome/repo/node_modules/@docusaurus/plugin-content-docs/lib/index.js:114:31)
2023-05-24T08:18:58.714268Z	    at async Promise.all (index 0)
2023-05-24T08:18:58.714387Z	    at async Object.loadContent (/opt/buildhome/repo/node_modules/@docusaurus/plugin-content-docs/lib/index.js:171:33)
2023-05-24T08:18:58.714515Z	    at async /opt/buildhome/repo/node_modules/@docusaurus/core/lib/server/plugins/index.js:53:46
2023-05-24T08:18:58.714641Z	    at async Promise.all (index 0)
2023-05-24T08:18:58.714763Z	    at async Object.loadPlugins (/opt/buildhome/repo/node_modules/@docusaurus/core/lib/server/plugins/index.js:52:34)
2023-05-24T08:18:58.714897Z	    at async Object.load (/opt/buildhome/repo/node_modules/@docusaurus/core/lib/server/index.js:94:82)
2023-05-24T08:18:58.715026Z	    at async buildLocale (/opt/buildhome/repo/node_modules/@docusaurus/core/lib/commands/build.js:80:19)
2023-05-24T08:18:58.715149Z	    at async tryToBuildLocale (/opt/buildhome/repo/node_modules/@docusaurus/core/lib/commands/build.js:32:20)
2023-05-24T08:18:58.715299Z	    at async Object.mapAsyncSequencial (/opt/buildhome/repo/node_modules/@docusaurus/utils/lib/index.js:328:24)
2023-05-24T08:18:58.715423Z	    at async build (/opt/buildhome/repo/node_modules/@docusaurus/core/lib/commands/build.js:68:25)
2023-05-24T08:18:58.72047Z	npm ERR! code ELIFECYCLE
2023-05-24T08:18:58.72068Z	npm ERR! errno 1
2023-05-24T08:18:58.724982Z	npm ERR! nucleus-docs@0.0.0 build: `npm run getTokens && docusaurus build`
2023-05-24T08:18:58.72579Z	npm ERR! Exit status 1
2023-05-24T08:18:58.726012Z	npm ERR! 
2023-05-24T08:18:58.726165Z	npm ERR! Failed at the nucleus-docs@0.0.0 build script.
2023-05-24T08:18:58.726305Z	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2023-05-24T08:18:58.732527Z	
2023-05-24T08:18:58.732777Z	npm ERR! A complete log of this run can be found in:
2023-05-24T08:18:58.732935Z	npm ERR!     /opt/buildhome/.npm/_logs/2023-05-24T08_18_58_726Z-debug.log
2023-05-24T08:18:58.743046Z	Failed: build command exited with code: 1
2023-05-24T08:18:59.588091Z	Failed: error occurred while running build command

**Comment by jholt1** [comment]
@RobTobias123 You can't delete a page and then still have it referenced in the sidebar https://github.com/centrica-engineering/nucleus-docs/blob/main/sidebars.js#L35

**Comment by RobTobias123** [comment]
Reviewed, approved and merged.
